version: '3.7'
services:
  db:
    image: mariadb:latest
    container_name: mydb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: diary
      MYSQL_USER: master
      MYSQL_PASSWORD: mypw
